apiVersion: v1
kind: Pod
metadata:
  name: server-pod-productservice
  labels:
    name: server-pod-productservice
    app: cluster-1

spec:
  containers:
    - name: server-pod-productservice
      image: it19020822/cluster-1
      ports:
        - containerPort: 5000
