apiVersion: v1
kind: Service
metadata:
  name: server-pod-productservice
  labels:
    name: server-pod-productservice
    app: cluster-1

spec:
  type: LoadBalancer
  ports:
    - port: 8090
      targetPort: 5000
  selector:
    name: server-pod-productservice
    app: cluster-1
